In [1]:
# Create a NumPy array representing the number of likes on 7 Instagram posts 
#  and print its ndim, shape, size, dtype, itemsize, and nbytes properties.

import numpy as np
likes = np.array([120, 250, 340, 180, 500, 275, 410])

print("Array:", likes)
print("ndim:", likes.ndim)
print("shape:", likes.shape)
print("size:", likes.size)
print("dtype:", likes.dtype)
print("itemsize:", likes.itemsize)
print("nbytes:", likes.nbytes)

Array: [120 250 340 180 500 275 410]
ndim: 1
shape: (7,)
size: 7
dtype: int64
itemsize: 8
nbytes: 56


In [2]:
#2. Given a 2D NumPy array of daily step counts for 5 days (each row is a day, columns are morning and evening),
# use reshape() to convert it into a 1D array, then back to a 2D array with 5 rows and 2 columns.
# <br><br><em><strong>Hint:</strong> Use the shape attribute to check your array after each reshape.</em>

import numpy as np

steps = np.array([
    [2500, 3000],
    [2800, 3500],
    [2200, 3200],
    [3000, 4000],
    [2700, 3600]
])

print("Original array:")
print(steps)
print("Original shape:", steps.shape)

steps_1d = steps.reshape(-1)

print("\n1D array:")
print(steps_1d)
print("1D shape:", steps_1d.shape)

steps_2d = steps_1d.reshape(5, 2)

print("\nBack to 2D array:")
print(steps_2d)
print("2D shape:", steps_2d.shape)

Original array:
[[2500 3000]
 [2800 3500]
 [2200 3200]
 [3000 4000]
 [2700 3600]]
Original shape: (5, 2)

1D array:
[2500 3000 2800 3500 2200 3200 3000 4000 2700 3600]
1D shape: (10,)

Back to 2D array:
[[2500 3000]
 [2800 3500]
 [2200 3200]
 [3000 4000]
 [2700 3600]]
2D shape: (5, 2)


In [3]:
# 3. Build a NumPy array representing the prices of 12 food items from a Zomato order, then use ravel(), 
#  flatten(), and resize()to create different shaped versions of the data and print each result.
#  <br><br><em><strong>Constraint:</strong> Show the difference between ravel() and flatten() in your code 
#  comments.</em>

import numpy as np

prices = np.array([
    [120, 150, 80, 200],
    [90, 175, 110, 250],
    [130, 95, 180, 220]
])

print("Original Array:")
print(prices)
print("Original Shape:", prices.shape)

ravel_prices = prices.ravel()

print("\nUsing ravel():")
print(ravel_prices)
print("Shape:", ravel_prices.shape)

flatten_prices = prices.flatten()

print("\nUsing flatten():")
print(flatten_prices)
print("Shape:", flatten_prices.shape)

prices.resize(2, 6)

print("\nUsing resize():")
print(prices)
print("Shape:", prices.shape)

Original Array:
[[120 150  80 200]
 [ 90 175 110 250]
 [130  95 180 220]]
Original Shape: (3, 4)

Using ravel():
[120 150  80 200  90 175 110 250 130  95 180 220]
Shape: (12,)

Using flatten():
[120 150  80 200  90 175 110 250 130  95 180 220]
Shape: (12,)

Using resize():
[[120 150  80 200  90 175]
 [110 250 130  95 180 220]]
Shape: (2, 6)


In [4]:
# 4. Take a 3x3 NumPy array representing a mini Spotify playlist grid (rows: playlists, columns: 
#    song counts in categories like Pop, Rock, Indie). Use both T and np.transpose() to swap rows and columns, 
#    then print the transposed array.

import numpy as np

playlist = np.array([
    [10, 5, 8],    
    [7, 12, 6],    
    [9, 4, 11]     
])

print("Original Playlist Grid:")
print(playlist)

transposed_T = playlist.T

print("\nUsing T:")
print(transposed_T)

transposed_np = np.transpose(playlist)

print("\nUsing np.transpose():")
print(transposed_np)

Original Playlist Grid:
[[10  5  8]
 [ 7 12  6]
 [ 9  4 11]]

Using T:
[[10  7  9]
 [ 5 12  4]
 [ 8  6 11]]

Using np.transpose():
[[10  7  9]
 [ 5 12  4]
 [ 8  6 11]]


In [5]:
# 5. Given a 1D NumPy array of 15 Flipkart product ratings, use reshape() to convert it into a 3x5 array, 
#  then use flatten() to return it to a 1D array. Explain in a comment when you would use flatten() 
#  versus ravel() in real projects.

import numpy as np

ratings = np.array([
    4.5, 4.0, 3.5, 5.0, 4.2,
    3.8, 4.7, 4.1, 3.9, 4.8,
    4.3, 3.6, 4.9, 4.4, 3.7
])

print("Original 1D Array:")
print(ratings)
print("Shape:", ratings.shape)

ratings_2d = ratings.reshape(3, 5)

print("\n3x5 Array:")
print(ratings_2d)
print("Shape:", ratings_2d.shape)

ratings_1d = ratings_2d.flatten()

print("\nAfter flatten():")
print(ratings_1d)
print("Shape:", ratings_1d.shape)


Original 1D Array:
[4.5 4.  3.5 5.  4.2 3.8 4.7 4.1 3.9 4.8 4.3 3.6 4.9 4.4 3.7]
Shape: (15,)

3x5 Array:
[[4.5 4.  3.5 5.  4.2]
 [3.8 4.7 4.1 3.9 4.8]
 [4.3 3.6 4.9 4.4 3.7]]
Shape: (3, 5)

After flatten():
[4.5 4.  3.5 5.  4.2 3.8 4.7 4.1 3.9 4.8 4.3 3.6 4.9 4.4 3.7]
Shape: (15,)
