In [1]:
# 1. Create two NumPy arrays representing the number of likes on your last 7 Instagram posts and your friend's 
#    last 7 posts, then use np.add() and np.subtract() to calculate both the combined and difference arrays.

import numpy as np

my_likes = np.array([120, 250, 180, 300, 220, 275, 350])

friend_likes = np.array([150, 200, 190, 280, 250, 260, 320])

combined = np.add(my_likes, friend_likes)

difference = np.subtract(my_likes, friend_likes)

print("My Likes:", my_likes)
print("Friend's Likes:", friend_likes)
print("Combined Likes:", combined)
print("Difference:", difference)

My Likes: [120 250 180 300 220 275 350]
Friend's Likes: [150 200 190 280 250 260 320]
Combined Likes: [270 450 370 580 470 535 670]
Difference: [-30  50 -10  20 -30  15  30]


In [2]:
# 2. Given a NumPy array of item prices from your last Zomato order, 
#   use np.multiply() to apply a 10% discount on each item, then use np.sum() 
#   to calculate the final bill amount after discount.<br><br><em><strong>Hint:</strong> 
#   To apply a 10% discount, multiply each price by 0.9.</em>

import numpy as np

prices = np.array([250, 180, 320, 150, 400])

discounted_prices = np.multiply(prices, 0.9)

final_bill = np.sum(discounted_prices)

print("Original Prices:", prices)
print("Prices after 10% discount:", discounted_prices)
print("Final Bill Amount:", final_bill)

Original Prices: [250 180 320 150 400]
Prices after 10% discount: [225. 162. 288. 135. 360.]
Final Bill Amount: 1170.0


In [3]:
# 3. Take a NumPy array of daily step counts for the last 30 days (you can make up the numbers), 
#     and use np.mean(), np.median(), np.std(), and np.max() to analyze your fitness stats like a health app would.

import numpy as np

steps = np.array([
    4500, 6200, 5100, 7000, 5800,
    6400, 4900, 7200, 6800, 5500,
    6000, 7500, 5200, 6900, 8100,
    4700, 6300, 7100, 5900, 6600,
    5400, 7800, 6200, 7000, 5700,
    6500, 8200, 5300, 6800, 7600
])

print("Average Steps:", np.mean(steps))
print("Median Steps:", np.median(steps))
print("Standard Deviation:", np.std(steps))
print("Maximum Steps:", np.max(steps))

Average Steps: 6340.0
Median Steps: 6350.0
Standard Deviation: 989.141041510259
Maximum Steps: 8200


In [4]:
# 4. Create a NumPy array of 10 random float ratings (between 1 and 5) for a new movie on BookMyShow, 
#  then use np.round(), np.floor(), and np.ceil() to show how the rating would appear if rounded to the nearest
#  whole number, always rounded down, and always rounded up.

import numpy as np

ratings = np.array([
    4.7, 3.2, 4.5, 2.8, 3.9,
    4.1, 2.4, 4.8, 3.6, 4.3
])

print("Original Ratings:")
print(ratings)

print("\nRounded Ratings:")
print(np.round(ratings))

print("\nFloor Ratings:")
print(np.floor(ratings))

print("\nCeil Ratings:")
print(np.ceil(ratings))

Original Ratings:
[4.7 3.2 4.5 2.8 3.9 4.1 2.4 4.8 3.6 4.3]

Rounded Ratings:
[5. 3. 4. 3. 4. 4. 2. 5. 4. 4.]

Floor Ratings:
[4. 3. 4. 2. 3. 4. 2. 4. 3. 4.]

Ceil Ratings:
[5. 4. 5. 3. 4. 5. 3. 5. 4. 5.]


In [5]:
# 5. Use ChatGPT to generate Python code that calculates the percentage of songs you skipped in your 
#  last 20 Spotify plays using NumPy arrays and np.percentile(), then run the code and paste your output.
#  <br><br><em><strong>Hint:</strong> Ask ChatGPT for code that finds the 75th percentile of skips in a NumPy 
#  array.</em> 

import numpy as np

skips = np.array([
    0, 1, 0, 1, 1,
    0, 0, 1, 0, 1,
    0, 1, 0, 0, 1,
    1, 0, 1, 0, 1
])

percentile_75 = np.percentile(skips, 75)

skip_percentage = np.mean(skips) * 100

print("Spotify Skip Data:", skips)
print("75th Percentile:", percentile_75)
print("Percentage of Songs Skipped:", skip_percentage, "%")

Spotify Skip Data: [0 1 0 1 1 0 0 1 0 1 0 1 0 0 1 1 0 1 0 1]
75th Percentile: 1.0
Percentage of Songs Skipped: 50.0 %
