In [1]:
# 1. Create a NumPy array called prices with the following values: [199, 299, 399, 499, 599]. 
#  Use basic indexing to print the first and last price.

import numpy as np

prices = np.array([199, 299, 399, 499, 599])

print("First price:", prices[0])
print("Last price:", prices[-1])

First price: 199
Last price: 599


In [2]:
# 2. Given a 2D NumPy array representing cricket scores for 3 players across 5 matches, 
#  use slicing to extract the scores of all players for matches 2 to 4 (index 1 to 3).

import numpy as np
scores = np.array([
    [45, 60, 72, 55, 80],
    [30, 50, 65, 70, 75],
    [55, 40, 68, 82, 90]
])
result = scores[:, 1:4]

print("Scores for matches 2 to 4:")
print(result)

Scores for matches 2 to 4:
[[60 72 55]
 [50 65 70]
 [40 68 82]]


In [3]:
# 3. You have a NumPy array called ratings = np.array([4.5, 3.8, 4.2, 2.9, 5.0, 3.5]). 
#  Use negative indexing to print the last three ratings.

import numpy as np

ratings = np.array([4.5, 3.8, 4.2, 2.9, 5.0, 3.5])

print("Last three ratings:", ratings[-3:])

Last three ratings: [2.9 5.  3.5]


In [4]:
# 4. Create a NumPy array of the first 20 natural numbers. Use step slicing to print every 3rd number starting from the second element.
#  <br><br><em><strong>Hint:</strong> Use the slice notation with a step value.</em>

import numpy as np

numbers = np.arange(1, 21)
result = numbers[1::3]

print("Numbers:", numbers)
print("Every 3rd number starting from second element:", result)

Numbers: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Every 3rd number starting from second element: [ 2  5  8 11 14 17 20]


In [5]:
# 5. Given a NumPy array of Flipkart product prices, use boolean indexing to extract 
#  all prices greater than 500.Print the resulting array.

import numpy as np

prices = np.array([250, 650, 450, 800, 550, 300, 1200])
result = prices[prices > 500]

print("Prices greater than 500:", result)

Prices greater than 500: [ 650  800  550 1200]


In [6]:
# 6. You have an array of IPL team scores: np.array([210, 180, 195, 220, 205, 175]).
# Use np.where() to find the indices of all scores above 200 and print these indices.

import numpy as np

scores = np.array([210, 180, 195, 220, 205, 175])
indices = np.where(scores > 200)

print("Indices of scores above 200:", indices[0])

Indices of scores above 200: [0 3 4]
