In [1]:
# 1. 

import numpy as np

zomato = np.array([4.5, 4.2, 3.8, 4.7, 4.0])
swiggy = np.array([4.1, 3.9, 4.6, 4.3, 4.8])

combined = np.concatenate((zomato, swiggy))

print("Zomato Ratings:", zomato)
print("Swiggy Ratings:", swiggy)
print("Combined Ratings:", combined)

Zomato Ratings: [4.5 4.2 3.8 4.7 4. ]
Swiggy Ratings: [4.1 3.9 4.6 4.3 4.8]
Combined Ratings: [4.5 4.2 3.8 4.7 4.  4.1 3.9 4.6 4.3 4.8]


In [2]:
# 2. 

import numpy as np

post1 = np.array([120, 150, 180, 200, 220, 250, 280])
post2 = np.array([100, 130, 160, 190, 210, 230, 260])
post3 = np.array([90, 120, 150, 170, 200, 240, 270])

stacked = np.vstack((post1, post2, post3))

print("Stacked Array:")
print(stacked)

Stacked Array:
[[120 150 180 200 220 250 280]
 [100 130 160 190 210 230 260]
 [ 90 120 150 170 200 240 270]]


In [3]:
# 3.

import numpy as np

product_ids = np.array([
    101, 102, 103, 104, 105, 106,
    107, 108, 109, 110, 111, 112
])

parts = np.array_split(product_ids, 5)

for i, part in enumerate(parts, start=1):
    print(f"Part {i}:", part)
    print("Shape:", part.shape)

Part 1: [101 102 103]
Shape: (3,)
Part 2: [104 105 106]
Shape: (3,)
Part 3: [107 108]
Shape: (2,)
Part 4: [109 110]
Shape: (2,)
Part 5: [111 112]
Shape: (2,)


In [4]:
# 4. 

import numpy as np
chat = np.array([
    [20, 15, 25, 18, 30, 22, 10],   # User 1
    [10, 12, 15, 20, 18, 15, 10],   # User 2
    [25, 20, 30, 22, 35, 28, 20]    # User 3
])

print("Original Chat Data:")
print(chat)

new_user = np.array([5, 8, 10, 7, 6, 9, 5])
chat = np.insert(chat, 3, new_user, axis=0)

print("\nAfter Adding New User:")
print(chat)
totals = np.sum(chat, axis=1)

print("\nTotal Messages by Each User:", totals)
least_user = np.argmin(totals)
chat = np.delete(chat, least_user, axis=0)

print("\nAfter Removing User with Least Messages:")
print(chat)

Original Chat Data:
[[20 15 25 18 30 22 10]
 [10 12 15 20 18 15 10]
 [25 20 30 22 35 28 20]]

After Adding New User:
[[20 15 25 18 30 22 10]
 [10 12 15 20 18 15 10]
 [25 20 30 22 35 28 20]
 [ 5  8 10  7  6  9  5]]

Total Messages by Each User: [140 100 180  50]

After Removing User with Least Messages:
[[20 15 25 18 30 22 10]
 [10 12 15 20 18 15 10]
 [25 20 30 22 35 28 20]]


In [5]:
# 5. 

import numpy as np

views = np.array([1000, 2500, 5000, 7500, 10000])

views_view = views.view()
views_copy = views.copy()

views_view[0] = 9999
views_copy[0] = 8888

print("Original Array:", views)
print("View Array:", views_view)
print("Copy Array:", views_copy)

Original Array: [ 9999  2500  5000  7500 10000]
View Array: [ 9999  2500  5000  7500 10000]
Copy Array: [ 8888  2500  5000  7500 10000]
